# Generated by Django 2.1rc1 on 2018-09-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0003_post_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
    ]
