# Generated by Django 2.1rc1 on 2018-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0004_remove_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
